@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2ODg5MjE5Njd9.Kn0Y1vPpp1JEswQCLERP3JwgYIN5VZRfta-DU0dpKLk

GET http://localhost:3000/checkins.json 

###

GET http://localhost:3000/breweries.json 

###


PATCH http://localhost:3000/checkins/9.json 
Content-Type: application/json

{
  "comments": "just kidding, i loved it"
}

### 

POST http://localhost:3000/checkins.json 
Content-Type: application/json

{
  "brewery_id": "9348209",
  "user_id": 3,
  "rating": 1,
  "image_url": "image_url",
  "comments": "not great"
}

###

POST http://localhost:3000/breweries.json 
Content-Type: application/json

{
  "name": "Light the Lamp Brewery",
  "address": "2 S. Lake Street",
  "city": "Grayslake",
  "state": "Illinois",
  "zip": 60030,
  "tap_list": "https://www.lightthelampbrewery.com/general-5",
  "website_url": "https://www.lightthelampbrewery.com/",
  "latitude": "42.3441764",
  "longitude": "-88.0438977"
}

###

PATCH http://localhost:3000/breweries/205.json 
Content-Type: application/json

{
  "city": "Round Lake"
}

###

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "leah@example.com",
  "password": "password"
}

###

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test",
  "email": "Blah@test.com",
  "password": "test",
  "password_confirmation": "test"
}

###

DELETE http://localhost:3000/checkins/8.json 
Content-Type: application/json

###

DELETE http://localhost:3000/breweries/205.json 
Content-Type: application/json

###

DELETE http://localhost:3000/users/3.json 
Content-Type: application/json

###

# POST http://localhost:3000/users.json
# Content-Type: application/json

# {
#   "name": "Buster",
#   "email": "Buster@test.com",
#   "password": "bark",
#   "password_confirmation": "bark"
# }