@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2ODg3MzY3MjV9.xu6fYcrio5tqYq6FdBXtz-60Do09QxbDHX5R7asbuX4

GET http://localhost:3000/checkins.json 

###

GET http://localhost:3000/breweries.json 

###

POST http://localhost:3000/breweries.json 
Content-Type: application/json

{
  "name": "Light the Lamp Brewery",
  "address": "2 S. Lake Street",
  "city": "Grayslake",
  "state": "Illinois",
  "zip": 60030,
  "tap_list": "https://www.lightthelampbrewery.com/general-5",
  "website_url": "https://www.lightthelampbrewery.com/",
  "latitude": "42.3441764",
  "longitude": "-88.0438977",
}

###

PATCH http://localhost:3000/checkins/4.json 
Content-Type: application/json

{
  "comments": "wasn't a fan of this brewery"
}

### 

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Blah@test.com",
  "password": "test"
}

###

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test",
  "email": "Blah@test.com",
  "password": "test",
  "password_confirmation": "test"
}

###

DELETE http://localhost:3000/checkins/4.json 
Content-Type: application/json


# POST http://localhost:3000/users.json
# Content-Type: application/json

# {
#   "name": "Buster",
#   "email": "Buster@test.com",
#   "password": "bark",
#   "password_confirmation": "bark"
# }